Card and List Group Headers/Sections Styling
DNNCommunity/jekyll-theme-dnn-community pull request #13
Opened 2018-10-14 15:17 UTC by nvisionative

Updated card and list group headers/section styling to provide a more branded look and feel, as well as improve the overall user experience.
Resolves #12

2018-10-14 22:26 UTC, valadas requested changes
Added a few comments, if we can use variables instead of hardcoded colors, it will be easier to change them if the corporate colors ever change, we will have only the _variables.scss to modify.

2018-10-14 22:26 UTC, valadas commented on _sass/base/_base.scss
> +    background-color: #472A2B;
Can you please replace the hardcoded color with $theme-color("dark") it will be easier to maintain if the corporate colors ever change, we can just modify them in the _variables.scss (single place).

2018-10-14 22:26 UTC, valadas commented on _sass/base/_base.scss
> +    color: #00A4E4;
Can you please replace the hardcoded color with $theme-color("primary") it will be easier to maintain if the corporate colors ever change, we can just modify them in the _variables.scss (single place).

2018-10-14 22:26 UTC, valadas commented on _sass/base/_base.scss
> +    color: #00A4E4;
Can you please replace the hardcoded color with $theme-color("primary") it will be easier to maintain if the corporate colors ever change, we can just modify them in the _variables.scss (single place).

2018-10-15 01:45 UTC, nvisionative commented on _sass/base/_base.scss
> +    background-color: #472A2B;
Thanks for the tip - you are absolutely right.

2018-10-15 01:45 UTC, nvisionative commented on _sass/base/_base.scss
> +    color: #00A4E4;
Thanks for the tip - you are absolutely right.

2018-10-15 01:45 UTC, nvisionative commented on _sass/base/_base.scss
> +    color: #00A4E4;
Thanks for the tip - you are absolutely right.

2018-10-15 01:47 UTC, nvisionative commented
@valadas a new commit was just pushed to address the issues you mentioned.  Thanks!

2018-10-15 01:57 UTC, valadas approved these changes

2018-10-15 01:57 UTC, merged